### ISSUE TITLE
Invalid Cast Exception when Retrieving a list of Chats

### ISSUE THREAD

**Issue by AdamHong** [Parature/ParatureSDK#12]
Date Created, Date Ended, and Is Anonymous is not deserializing correctly for Chats

**Comment by brtubb** [comment]
Fixed, but the Transcripts and the History aren't being deserialized

**Comment by brtubb** [comment]
This is now fixed. There may be other Target/Performer types (ActionHistory.ActionHistoryTarget or Performer) that we haven't seen before, so we'll need to keep an eye on exceptions getting thrown due to broken deserialization...
