### ISSUE TITLE
Not retrieving all entities iteratively

### ISSUE THREAD

**Issue by brtubb** [Parature/ParatureSDK#14]
When RetrieveAllRecords = true in a query, all entities should be iteratively retrieved. Instead, it's stopping at the first retrieval.

**Comment by brtubb** [comment]
Issue is when implementing the IEnumerable interface.
http://stackoverflow.com/questions/4726095/xmlserializer-and-ienumerable-serialization-possible-w-o-parameterless-construc

IEnumerable has its own IXmlSerializable replacement for the default Xml serializing behavior

**Comment by AdamHong** [comment]
Fixed in https://github.com/Parature/ParatureSDK/commit/9d4bc841dcba3a59d7505755b215e10f4640b9a5 with a custom XmlSerializer
