### ISSUE TITLE
Cannot add attachments to new Ticket

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#15]
When creating a new Ticket I can add attachments to the ticket before it is created; but the attachments do not show up against the ticket in Parature.

I'm using the code below.
The ticket is created successfully, and the call to AttachmentAdd gets an attachment GIUD; but the attachment does not show on the ticket in the portal.

                var ticket = new ParatureSDK.ParaObjects.Ticket();
                ticket.Ticket_Customer = new ParatureSDK.ParaObjects.EntityReferences.CustomerReference()
                {
                    Entity = customer,
                };
                ticket.CustomFieldSetValue(49, "Test ticket from API - text area field");
                ticket.CustomFieldSetValue(50, "Test ticket from API - summary field");

                ticket.Ticket_Attachments = new List<ParatureSDK.ParaObjects.Attachment>();
                ticket.AttachmentsAdd(creds, "Attachment Text", "text/plain", "TestAttachment.txt");

                var response = ParatureSDK.ApiHandler.Ticket.Insert(ticket, creds);
                if (response.HasException)
                {
                    Console.WriteLine(response.ExceptionDetails);
                }

**Comment by brtubb** [comment]
This should be resolved in master now. Please alert us if you have more issues! I will push to NuGet later today.
