### ISSUE TITLE
Ticket.AttachmentsDelete throws exception

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#20]
Removing an element from a list is not permitted while iterating over the list.

An alternate way to do this is:
```
    var attachment = Ticket_Attachments.Find((x) => x.Guid == AttachmentGuid);
    if (attachment != null)
        Ticket_Attachments.Remove(attachment);
```

**Comment by brtubb** [comment]
The AttachmentsDelete method is pretty old; thanks for letting us know if this issue!

To add to this, there is no support for deleting ALL attachments right now. If the attachments list is empty (count = 0) then the XML node isn't created. To remove all attachments, an empty Ticket_Attachments node would need to be sent back to the server.

I'm debating whether a flag would be the way to indicate that we do indeed want to delete all attachments on a ticket. Last thing we want is to accidentally delete attachments... May be a new Update.

This is definitely a bug, and will be closed once both issues are addressed.

**Comment by brtubb** [comment]
Did not mean to close.

**Comment by brtubb** [comment]
This has been rectified in master. Added a method to delete all attachments as well.

We've struggled with adding this capability, as it could open an easy way for someone to accidentally delete attachments. We wanted this to be an explicit desire, so deleting all attachments MUST go through the ticket.DeleteAllAttachments or ticket.AttachmentsDelete(guid) methods.
