### ISSUE TITLE
ParaEnums.QueryCriteria.MoreThan is actually a >= comparison.

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#23]
The comments in the code state it is a '>' comparison; but it will return records that are equal to the specified date. The API documentation states that the date comparison is '>='.

Similarly LessThan is actually <=

Phil.

**Comment by brtubb** [comment]
Thanks! Investigating...

**Comment by brtubb** [comment]
This is correct according to the public API documentation. However, this is a bug purely for dates. Numeric MoreThan and LessThan are truly ">" and "<" respectively, as per the docs. This will be clarified in the comments.

**Comment by brtubb** [comment]
Fixed and in master
