### ISSUE TITLE
Date filters in queries do not include the milliseconds value in the REST API call

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#25]
ParaQuery.AddStaticFieldFilter and ParaQuery.AddCustomFieldFilter do not include the milliseconds part of the DateTime value parameter in the query string.

This can result in extra records being retrieved even though the date on the record is outside the expected query range.

**Comment by brtubb** [comment]
I'll take a look and see if millisecond filtering is possible in the API. Will classify as a bug after verifying.

**Comment by brtubb** [comment]
Definitely a bug, looks like go down to the millisecond. Thank you for reporting! Should be a simple fix.

**Comment by brtubb** [comment]
@philmoz Fixed in master. Our APIs do indeed filter down to the millisecond. Thank you for pointing this out!
