### ISSUE TITLE
ActionHistory.Cc_Csr and ActionHistory.Cc_Customer not deserialized from REST API results.

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#27]
The data types for ActionHistory.Cc_Csr and ActionHistory.Cc_Customer are ArrayList; but the data in the REST API results are strings.

Changing these to string type in the ActionHistory class seems to fix the deserilaization.

**Comment by brtubb** [comment]
Definite bug. Should be a simple fix.

**Comment by brtubb** [comment]
Completed and fixed in master.
