### ISSUE TITLE
Ticket.Additional_Contact does not appear to be mapped to any field in the REST API results.

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#28]
There does not appear to be any corresponding value in the REST API results that corresponds to the Ticket.Additional_Contact field.

Is this used at all?

**Comment by AdamHong** [comment]
Hi Phil,

The additional contact field needs to be added to an environment it to show up in the API. Its used with the consultant role so users can submit tickets on behalf of others. This is configuration is currently only available to Parature employees.

Thanks,
Adam
