### ISSUE TITLE
ParatureSDK.dll compiled for .NET 4.5 instead of 4.0

### ISSUE THREAD

**Issue by jimitndiaye** [Parature/ParatureSDK#29]
The latest Nuget package for ParatureSDK (v2.1.1) contains a .NET 4.5 dll instead of 4.0 even though the package metadata says it is 4.0. v2.0.10 is fine.

**Comment by brtubb** [comment]
As @AdamHong said, we'll circle back and support both .Net 4.0 and 4.5, starting with the latest 2.1.1 release and going forward. Will close this status after pushing an update.

**Comment by jimitndiaye** [comment]
Is there any ETA on this? I'm encountering a bug on the v2.0.10 release with xml generation of entity references (specifically customer reference) so I could use the update ASAP.
FYI, the following code fails with the error "No XML generation logic found for field type: entity"


        public static Ticket CreateTicket(string summary, string details, long customerId)
        {
            var ticket = ParatureSDK.ApiHandler.Ticket.Schema(CredentialProvider.Creds);
            ticket.Ticket_Customer = new CustomerReference {Customer = new Customer {Id = customerId}};
            ticket.CustomFieldSetValue(ticket.CustomFieldGetId("Summary"), summary);
            ticket.CustomFieldSetValue(ticket.CustomFieldGetId("Details"), details);

            var response = ParatureSDK.ApiHandler.Ticket.Insert(ticket, CredentialProvider.Creds);
            ticket.Id = response.Id;

            return ticket;
        }
The same code works with the latest SDK

**Comment by AdamHong** [comment]
We just published the latest release to nuget with both 4.0 and 4.5 binaries.
