### ISSUE TITLE
Cannot delete records with latest SDK changes.

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#35]
The ApiCallFactory.ObjectDelete<T> method is creating invalid URI's for the Parature API - as a result object deletion fails.

The call to ObjectDelete should pass 'typeof(T).Name' as the entityType parameter, not 'typeof(T).ToString()'.

**Comment by brtubb** [comment]
Hi @philmoz, is this in the stable branch 2.x? Thank you for bringing this to our attention.

**Comment by philmoz** [comment]
It's in the master branch and the 3.0.0.-prerelease branch.

**Comment by brtubb** [comment]
Confirmed. Working on fix. Thanks for the suggestion phil

**Comment by brtubb** [comment]
There is a defect with the APIs preventing a complete fix. We have a code fix coming shortly to master.

**Comment by AdamHong** [comment]
Resolved in v2.2.2. https://github.com/Parature/ParatureSDK/commit/816c2cd6a81538c21e10195023deccd2fa6dbe23
