### ISSUE TITLE
Add ability to pull an entity by id

### ISSUE THREAD

**Issue by tjohnson1010** [Parature/ParatureSDK#36]
The Parature API allows retrieving an entity by it's id.  This is done by adding /{id} before the ? in the uri.  I propose adding a long property to the entity class called id, which when non-zero, will will add the /id to the uri and add then add the token parameter.  FYI: All the other queryable fields are not usable in this scenario.

**Comment by brtubb** [comment]
@tjohnson1010 , do you mind expanding on your idea? We have methods that allow you to retrieve individual records by their long Id, matching the functionality of our API.

In the 3.0 branch, it's the ParaService.Get<T> method.
![image](https://cloud.githubusercontent.com/assets/10502971/10025258/61d4dc44-6129-11e5-98be-97b6f96fda85.png)

In 2.X (currently master), it's ApiHandler.<Entity>.GetDetails.
![image](https://cloud.githubusercontent.com/assets/10502971/10025333/bd5e7570-6129-11e5-909b-67ba181f8a70.png)

These add the id to the uri, the same as a GET in your browser.

**Comment by tjohnson1010** [comment]
Thank you.  You are correct.  I dug through the code to look for the correct method and I didn't find it because I was limiting my search to the GetList method. I'll close this request.
