### ISSUE TITLE
New non-Generic Delete method should be internal or private. Won't work without type

### ISSUE THREAD

**Issue by brtubb** [Parature/ParatureSDK#38]
Seeing two Delete methods. The non-Generic version isn't possible to use.
![image](https://cloud.githubusercontent.com/assets/10502971/10022488/20b9e136-611b-11e5-9714-e789e5740a33.png)

Seeing an error on usage:
![image](https://cloud.githubusercontent.com/assets/10502971/10022500/2bc83582-611b-11e5-87a4-1eb29aa2b637.png)

**Comment by AdamHong** [comment]
This is resolved. Removed the generic method as we only need one delete method. The non-generic method can be invoked by proving the type when calling like this:

service.Delete<Ticket>(id, true);

https://github.com/Parature/ParatureSDK/commit/174277f0f3516d4302d0659591e05245341f8bc2
