### ISSUE TITLE
Product Folder Creation

### ISSUE THREAD

**Issue by manishkdixit** [Parature/ParatureSDK#44]
While Trying to create a new product folder,  always get a response "The URI is not valid: Invalid Entity Type: Folder". 
Looks like URL formed is incorrect as it calls for "Folder" instead of Product Folder as displayed below

https://{hostname}//api/v1/{account id}/{department id}/Folder

Correct one seems to be: https://{hostname}/api/v1/{account id}/{department id}/ProductFolder

**Comment by AdamHong** [comment]
Hi Manish. This is resolved in the latest release of the SDK, v2.2.2. https://github.com/Parature/ParatureSDK/commit/ff1c3d416e1de5a2ccf9e0d34ccbe2f64d61f618
