### ISSUE TITLE
Account Xmlgenerator should do a null check for its Viewable_Account property

### ISSUE THREAD

**Issue by dwcai** [Parature/ParatureSDK#7]
When we try to create an account using Insert method, it will call XmlGenerator's GenerateXml method, which fails with an "Object reference not set to an instance of an object" error. The reason is Viewable_Account is null at the following line of code. 

```C#
if (obj.Viewable_Account.Count > 0)
```

Doing a null check (such as the following) should fix the issue. 
```C#
if (obj.Viewable_Account != null && obj.Viewable_Account.Count > 0)
```

**Comment by dwcai** [comment]
Also, the following line should do a similar null check. 
```C#
if (obj.Default_Customer_Role.Role.Id > 0)
```

**Comment by brtubb** [comment]
Thanks for pointing these out! Found another null check missing too, which will be covered in the next code push.

**Comment by brtubb** [comment]
Fixed in the latest code push and on Nuget (version 2.0.1)
