### ISSUE TITLE
Proxy and timeout support

### ISSUE THREAD

**Issue by dwcai** [Parature/ParatureSDK#8]
The SDK should have the support of the following configurations.
* Proxy connection (including the use of the proxy credentials)
* Service timeout

Thanks!

**Comment by brtubb** [comment]
This is now possible in the latest codepush on git. There is an Action<HttpWebRequest> you can set in ApiRequestSettings.GlobalPreRequest, which gets called right before each and every request now. 

```
ParatureSDK.ApiRequestSettings.GlobalPreRequest = (req) =>
{
   req.Timeout = 120*1000;
};
```
